export interface CaptionBlock {
  id: string;
  text: string;
  start: number; // in seconds
  end: number;   // in seconds
  x?: number;    // percentage 0-100 (optional)
  y?: number;    // percentage 0-100 (optional)
  rotation?: number; // tilt in degrees (optional)
}

export interface CaptionStyle {
  fontFamily: string;
  fontSize: number;
  fontWeight: 'normal' | 'bold';
  uppercase: boolean;
  textColor: string;      // #RRGGBB
  textOpacity: number;    // 0-1
  backgroundColor: string; // #RRGGBB
  backgroundOpacity: number; // 0-1
  strokeColor: string;    // #RRGGBB
  strokeWidth: number;    // 0-10
  shadowColor: string;    // #RRGGBB
  shadowWidth: number;    // 0-10
  glowColor?: string;     // #RRGGBB
  glowWidth?: number;     // 0-10
  opacity: number;        // 0-1
  animation: string;      // 'none' | 'fade' | 'slide-up' | 'pop' | 'scale'
  position: 'top' | 'center' | 'bottom' | 'custom';
}

function hexToAssColor(hex: string, opacity: number = 1): string {
  let cleanHex = hex.replace('#', '');
  if (cleanHex.length === 3) {
    cleanHex = cleanHex.split('').map(c => c + c).join('');
  }
  if (cleanHex.length !== 6) {
    cleanHex = 'FFFFFF';
  }
  
  const r = cleanHex.substring(0, 2);
  const g = cleanHex.substring(2, 4);
  const b = cleanHex.substring(4, 6);
  
  // Alpha: 00 is fully opaque, FF is fully transparent in ASS
  const alphaVal = Math.round((1 - opacity) * 255);
  const a = alphaVal.toString(16).padStart(2, '0').toUpperCase();
  
  return `&H${a}${b}${g}${r}`;
}

function formatTime(seconds: number): string {
  if (seconds < 0) seconds = 0;
  const h = Math.floor(seconds / 3600);
  const m = Math.floor((seconds % 3600) / 60);
  const s = Math.floor(seconds % 60);
  const cs = Math.floor((seconds % 1) * 100);
  
  const hStr = h.toString();
  const mStr = m.toString().padStart(2, '0');
  const sStr = s.toString().padStart(2, '0');
  const csStr = cs.toString().padStart(2, '0');
  
  return `${hStr}:${mStr}:${sStr}.${csStr}`;
}

export function generateAssFile(
  captions: CaptionBlock[],
  style: CaptionStyle,
  videoWidth: number = 1920,
  videoHeight: number = 1080
): string {
  const playResX = videoWidth;
  const playResY = videoHeight;

  // Process text casing
  const processText = (text: string) => {
    return style.uppercase ? text.toUpperCase() : text;
  };

  // Convert styles to ASS V4+ Styles
  const primaryColor = hexToAssColor(style.textColor, style.textOpacity * style.opacity);
  const secondaryColor = '&H0000FFFF'; // Default secondary for karaoke or highlight
  const outlineColor = hexToAssColor(style.strokeColor, style.opacity);
  
  // If we have background color with opacity, we use BorderStyle = 3 (Opaque Box)
  // Else we use BorderStyle = 1 (Outline + Shadow) and set BackColor as ShadowColor
  const borderStyle = style.backgroundOpacity > 0 ? 3 : 1;
  const backColor = borderStyle === 3 
    ? hexToAssColor(style.backgroundColor, style.backgroundOpacity * style.opacity)
    : hexToAssColor(style.shadowColor, style.opacity);

  const boldVal = style.fontWeight === 'bold' ? -1 : 0;
  
  // Alignment: 2 = bottom-center, 5 = center-center, 8 = top-center
  let alignment = 2;
  if (style.position === 'top') {
    alignment = 8;
  } else if (style.position === 'center') {
    alignment = 5;
  } else if (style.position === 'bottom') {
    alignment = 2;
  } else if (style.position === 'custom') {
    alignment = 2; // Default reference point when doing custom positions
  }

  // MarginV is the vertical height from the aligned edge
  let marginV = Math.round(playResY * 0.1); // default 10% from bottom
  if (style.position === 'top') {
    marginV = Math.round(playResY * 0.1); // 10% from top
  } else if (style.position === 'center') {
    marginV = 0; // middle
  }

  const lines: string[] = [];
  
  // Section 1: Script Info
  lines.push('[Script Info]');
  lines.push('; Script generated by CaptionFlow AI');
  lines.push('Title: CaptionFlow AI Subtitles');
  lines.push('ScriptType: v4.00+');
  lines.push('WrapStyle: 0');
  lines.push(`PlayResX: ${playResX}`);
  lines.push(`PlayResY: ${playResY}`);
  lines.push('ScaledBorderAndShadow: yes');
  lines.push('');

  // Section 2: Styles
  lines.push('[V4+ Styles]');
  lines.push('Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding');
  lines.push(`Style: CustomStyle,${style.fontFamily},${style.fontSize},${primaryColor},${secondaryColor},${outlineColor},${backColor},${boldVal},0,0,0,100,100,0,0,${borderStyle},${style.strokeWidth},${style.shadowWidth},${alignment},20,20,${marginV},1`);
  lines.push('');

  // Section 3: Events
  lines.push('[Events]');
  lines.push('Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text');

  for (const cap of captions) {
    const startStr = formatTime(cap.start);
    const endStr = formatTime(cap.end);
    let text = processText(cap.text);

    // Apply inline override tags for position, animation, etc.
    let tags = '';

    // Custom Position tag {\pos(x, y)}
    if (style.position === 'custom' && cap.x !== undefined && cap.y !== undefined) {
      // Map percentages to video coordinates
      const posX = Math.round((cap.x / 100) * playResX);
      const posY = Math.round((cap.y / 100) * playResY);
      tags += `\\pos(${posX},${posY})`;
    }

    // Custom rotation/tilt tag {\frz<degrees>}
    if (cap.rotation !== undefined && cap.rotation !== 0) {
      tags += `\\frz${cap.rotation}`;
    }

    // Animations (Fade, Slide Up, Pop)
    // times are in milliseconds
    const durationMs = (cap.end - cap.start) * 1000;
    if (style.animation === 'fade') {
      const fadeTime = Math.min(200, durationMs / 3);
      tags += `\\fad(${Math.round(fadeTime)},${Math.round(fadeTime)})`;
    } else if (style.animation === 'slide-up') {
      // Move from y+30 to y over 250ms
      const fadeTime = Math.min(250, durationMs / 2);
      if (style.position === 'custom' && cap.x !== undefined && cap.y !== undefined) {
        const posX = Math.round((cap.x / 100) * playResX);
        const posY = Math.round((cap.y / 100) * playResY);
        tags += `\\move(${posX},${posY + 30},${posX},${posY},0,${Math.round(fadeTime)})`;
      } else {
        // Standard position sliding up using relative movement is hard in ASS,
        // so we calculate a fallback pos based on alignment settings if not custom
        let posX = Math.round(playResX / 2);
        let posY = Math.round(playResY * 0.9); // bottom center fallback
        if (style.position === 'top') {
          posY = Math.round(playResY * 0.15);
        } else if (style.position === 'center') {
          posY = Math.round(playResY / 2);
        }
        tags += `\\move(${posX},${posY + 30},${posX},${posY},0,${Math.round(fadeTime)})`;
      }
    } else if (style.animation === 'pop' || style.animation === 'scale') {
      // Scale from 80% to 100% over 150ms
      // We can use \t transform tags for font scale: {\fscx80\fscy80\t(0,150,\fscx100\fscy100)}
      tags += `\\fscx80\\fscy80\\t(0,150,\\fscx100\\fscy100)`;
    } else if (style.animation === 'squeeze') {
      // Bouncy squeeze animation: initial squash (130% X, 60% Y), morph to stretch (85% X, 120% Y) at 120ms, settle at 220ms (100% X/Y)
      tags += `\\fscx130\\fscy60\\t(0,120,\\fscx85\\fscy120)\\t(120,220,\\fscx100\\fscy100)`;
    }

    const dialogueLine = tags ? `{\\an${alignment}${tags}}${text}` : text;
    lines.push(`Dialogue: 0,${startStr},${endStr},CustomStyle,,0,0,0,,${dialogueLine}`);
  }

  return lines.join('\n');
}
