import type { CaptionStyle, PresetType } from '../types';

export const PRESETS: Record<PresetType, { name: string; style: CaptionStyle }> = {
  'modern-white': {
    name: 'Modern White',
    style: {
      fontFamily: 'Arial',
      fontSize: 24,
      fontWeight: 'bold',
      uppercase: false,
      textColor: '#FFFFFF',
      textOpacity: 1,
      backgroundColor: '#000000',
      backgroundOpacity: 0,
      strokeColor: '#000000',
      strokeWidth: 1.5,
      shadowColor: '#000000',
      shadowWidth: 1,
      opacity: 1,
      animation: 'fade',
      position: 'bottom',
    },
  },
  'bold-tiktok': {
    name: 'Bold TikTok',
    style: {
      fontFamily: 'Impact',
      fontSize: 32,
      fontWeight: 'bold',
      uppercase: true,
      textColor: '#FFFF00', // Yellow
      textOpacity: 1,
      backgroundColor: '#000000',
      backgroundOpacity: 0,
      strokeColor: '#000000',
      strokeWidth: 3,
      shadowColor: '#000000',
      shadowWidth: 0,
      opacity: 1,
      animation: 'pop',
      position: 'center',
    },
  },
  'minimal': {
    name: 'Minimal',
    style: {
      fontFamily: 'Arial',
      fontSize: 20,
      fontWeight: 'normal',
      uppercase: false,
      textColor: '#FFFFFF',
      textOpacity: 0.9,
      backgroundColor: '#000000',
      backgroundOpacity: 0,
      strokeColor: '#000000',
      strokeWidth: 0.5,
      shadowColor: '#000000',
      shadowWidth: 0,
      opacity: 1,
      animation: 'none',
      position: 'bottom',
    },
  },
  'netflix': {
    name: 'Netflix Style',
    style: {
      fontFamily: 'Arial',
      fontSize: 22,
      fontWeight: 'normal',
      uppercase: false,
      textColor: '#FFFFFF',
      textOpacity: 1,
      backgroundColor: '#000000',
      backgroundOpacity: 0.65, // Opaque box background
      strokeColor: '#000000',
      strokeWidth: 0,
      shadowColor: '#000000',
      shadowWidth: 0,
      opacity: 1,
      animation: 'none',
      position: 'bottom',
    },
  },
  'cinematic': {
    name: 'Cinematic',
    style: {
      fontFamily: 'Georgia',
      fontSize: 18,
      fontWeight: 'normal',
      uppercase: false,
      textColor: '#E5E5E5',
      textOpacity: 0.95,
      backgroundColor: '#000000',
      backgroundOpacity: 0,
      strokeColor: '#000000',
      strokeWidth: 1,
      shadowColor: '#000000',
      shadowWidth: 0,
      opacity: 1,
      animation: 'fade',
      position: 'bottom',
    },
  },
  'soft-shadow': {
    name: 'Soft Shadow',
    style: {
      fontFamily: 'Arial',
      fontSize: 24,
      fontWeight: 'bold',
      uppercase: false,
      textColor: '#FFFFFF',
      textOpacity: 1,
      backgroundColor: '#000000',
      backgroundOpacity: 0,
      strokeColor: '#000000',
      strokeWidth: 0,
      shadowColor: '#000000',
      shadowWidth: 3, // soft drop shadow
      opacity: 1,
      animation: 'fade',
      position: 'bottom',
    },
  },
  'neon': {
    name: 'Neon Green',
    style: {
      fontFamily: 'Arial',
      fontSize: 28,
      fontWeight: 'bold',
      uppercase: true,
      textColor: '#39FF14', // Neon Green
      textOpacity: 1,
      backgroundColor: '#000000',
      backgroundOpacity: 0,
      strokeColor: '#39FF14',
      strokeWidth: 1,
      shadowColor: '#39FF14',
      shadowWidth: 2, // simulated glow
      glowColor: '#39FF14',
      glowWidth: 6,
      opacity: 1,
      animation: 'pop',
      position: 'center',
    },
  },
  'luxury': {
    name: 'Luxury Gold',
    style: {
      fontFamily: 'Georgia',
      fontSize: 24,
      fontWeight: 'normal',
      uppercase: false,
      textColor: '#DFBA73', // Gold
      textOpacity: 1,
      backgroundColor: '#000000',
      backgroundOpacity: 0,
      strokeColor: '#000000',
      strokeWidth: 1,
      shadowColor: '#000000',
      shadowWidth: 1,
      opacity: 1,
      animation: 'fade',
      position: 'bottom',
    },
  },
  'apple': {
    name: 'Apple Style',
    style: {
      fontFamily: 'Arial',
      fontSize: 20,
      fontWeight: 'bold',
      uppercase: false,
      textColor: '#FFFFFF',
      textOpacity: 1,
      backgroundColor: '#1C1C1E',
      backgroundOpacity: 0.8, // rounded glassmorphic background box
      strokeColor: '#000000',
      strokeWidth: 0,
      shadowColor: '#000000',
      shadowWidth: 0,
      opacity: 1,
      animation: 'slide-up',
      position: 'bottom',
    },
  },
  'floating': {
    name: 'Floating Subtitle',
    style: {
      fontFamily: 'Arial',
      fontSize: 26,
      fontWeight: 'bold',
      uppercase: false,
      textColor: '#FFFFFF',
      textOpacity: 1,
      backgroundColor: '#000000',
      backgroundOpacity: 0,
      strokeColor: '#000000',
      strokeWidth: 2.5,
      shadowColor: '#000000',
      shadowWidth: 1.5,
      opacity: 1,
      animation: 'slide-up',
      position: 'bottom',
    },
  },
};
