import type { CaptionStyle, PresetType } from '../types';

export const PRESETS: Record<PresetType, { name: string; style: CaptionStyle }> = {
  'condensed-yellow': {
    name: 'Condensed Yellow',
    style: {
      fontFamily: 'Bebas Neue',
      fontSize: 32,
      fontWeight: 'bold',
      uppercase: false,
      textColor: '#FFCC00',
      textOpacity: 1,
      backgroundColor: '#000000',
      backgroundOpacity: 0,
      strokeColor: '#000000',
      strokeWidth: 0, // no outline
      shadowColor: '#000000',
      shadowWidth: 0, // no shadow
      opacity: 1,
      animation: 'fade',
      position: 'bottom',
    },
  },
  'bold-clean': {
    name: 'Bold Clean',
    style: {
      fontFamily: 'Outfit',
      fontSize: 30,
      fontWeight: 'bold',
      uppercase: false,
      textColor: '#FFFFFF',
      textOpacity: 1,
      backgroundColor: '#000000',
      backgroundOpacity: 0,
      strokeColor: '#000000',
      strokeWidth: 0,
      shadowColor: '#000000',
      shadowWidth: 0,
      opacity: 1,
      animation: 'fade',
      position: 'bottom',
    },
  },
  'condensed-uppercase': {
    name: 'Condensed Uppercase',
    style: {
      fontFamily: 'Bebas Neue',
      fontSize: 32,
      fontWeight: 'bold',
      uppercase: true,
      textColor: '#FFFFFF',
      textOpacity: 1,
      backgroundColor: '#000000',
      backgroundOpacity: 0,
      strokeColor: '#000000',
      strokeWidth: 0,
      shadowColor: '#000000',
      shadowWidth: 0,
      opacity: 1,
      animation: 'fade',
      position: 'bottom',
    },
  },
  'typewriter-bold': {
    name: 'Typewriter Bold',
    style: {
      fontFamily: 'Courier Prime',
      fontSize: 26,
      fontWeight: 'bold',
      uppercase: false,
      textColor: '#FFFFFF',
      textOpacity: 1,
      backgroundColor: '#000000',
      backgroundOpacity: 0,
      strokeColor: '#000000',
      strokeWidth: 0,
      shadowColor: '#000000',
      shadowWidth: 0,
      opacity: 1,
      animation: 'none',
      position: 'bottom',
    },
  },
  'sans-thin': {
    name: 'Sans Thin',
    style: {
      fontFamily: 'Outfit',
      fontSize: 24,
      fontWeight: 'normal',
      uppercase: false,
      textColor: '#FFFFFF',
      textOpacity: 1,
      backgroundColor: '#000000',
      backgroundOpacity: 0,
      strokeColor: '#000000',
      strokeWidth: 0,
      shadowColor: '#000000',
      shadowWidth: 0,
      opacity: 1,
      animation: 'fade',
      position: 'bottom',
    },
  },
  'fisheye': {
    name: 'Fish Eye Italic',
    style: {
      fontFamily: 'Playfair Display',
      fontSize: 34,
      fontWeight: 'bold',
      uppercase: false,
      textColor: '#FFFF00', // Yellow
      textOpacity: 1,
      backgroundColor: '#000000',
      backgroundOpacity: 0,
      strokeColor: '#000000',
      strokeWidth: 0,
      shadowColor: '#000000',
      shadowWidth: 0,
      opacity: 1,
      animation: 'fisheye', // signals italicized serif text style
      position: 'bottom',
    },
  },
};
