import type { CaptionStyle, PresetType } from '../types';

export const PRESETS: Record<PresetType, { name: string; style: CaptionStyle }> = {
  'modern-white': {
    name: 'Neo Sans (Clean)',
    style: {
      fontFamily: 'Outfit',
      fontSize: 26,
      fontWeight: 'bold',
      uppercase: false,
      textColor: '#FFFFFF',
      textOpacity: 1,
      backgroundColor: '#000000',
      backgroundOpacity: 0.4,
      strokeColor: '#000000',
      strokeWidth: 0,
      shadowColor: '#000000',
      shadowWidth: 2,
      opacity: 1,
      animation: 'fade',
      position: 'bottom',
    },
  },
  'bold-tiktok': {
    name: 'Condensed Impact',
    style: {
      fontFamily: 'Bebas Neue',
      fontSize: 34,
      fontWeight: 'bold',
      uppercase: true,
      textColor: '#FFFF00', // Yellow
      textOpacity: 1,
      backgroundColor: '#000000',
      backgroundOpacity: 0,
      strokeColor: '#000000',
      strokeWidth: 3.5,
      shadowColor: '#000000',
      shadowWidth: 0,
      opacity: 1,
      animation: 'pop',
      position: 'center',
    },
  },
  'minimal': {
    name: 'Classic Minimal',
    style: {
      fontFamily: 'Outfit',
      fontSize: 22,
      fontWeight: 'normal',
      uppercase: false,
      textColor: '#FFFFFF',
      textOpacity: 0.95,
      backgroundColor: '#000000',
      backgroundOpacity: 0,
      strokeColor: '#000000',
      strokeWidth: 0.5,
      shadowColor: '#000000',
      shadowWidth: 0,
      opacity: 1,
      animation: 'none',
      position: 'bottom',
    },
  },
  'netflix': {
    name: 'Typewriter Box',
    style: {
      fontFamily: 'Courier Prime',
      fontSize: 22,
      fontWeight: 'normal',
      uppercase: false,
      textColor: '#FFFFFF',
      textOpacity: 1,
      backgroundColor: '#000000',
      backgroundOpacity: 0.85, // solid type writer box
      strokeColor: '#000000',
      strokeWidth: 0,
      shadowColor: '#000000',
      shadowWidth: 0,
      opacity: 1,
      animation: 'none',
      position: 'bottom',
    },
  },
  'cinematic': {
    name: 'Editorial Chic',
    style: {
      fontFamily: 'Playfair Display',
      fontSize: 24,
      fontWeight: 'normal',
      uppercase: false,
      textColor: '#FFFFFF',
      textOpacity: 1,
      backgroundColor: '#000000',
      backgroundOpacity: 0,
      strokeColor: '#000000',
      strokeWidth: 0,
      shadowColor: '#000000',
      shadowWidth: 2,
      opacity: 1,
      animation: 'fade',
      position: 'bottom',
    },
  },
  'soft-shadow': {
    name: 'Bubble Candy',
    style: {
      fontFamily: 'Fredoka',
      fontSize: 26,
      fontWeight: 'bold',
      uppercase: false,
      textColor: '#FFFFFF',
      textOpacity: 1,
      backgroundColor: '#FF2A7A', // Neon pink box
      backgroundOpacity: 0.9,
      strokeColor: '#000000',
      strokeWidth: 0,
      shadowColor: '#000000',
      shadowWidth: 0,
      opacity: 1,
      animation: 'pop',
      position: 'center',
    },
  },
  'neon': {
    name: 'Neon Glow',
    style: {
      fontFamily: 'Poppins',
      fontSize: 28,
      fontWeight: 'bold',
      uppercase: true,
      textColor: '#FFFFFF',
      textOpacity: 1,
      backgroundColor: '#000000',
      backgroundOpacity: 0,
      strokeColor: '#FF007F', // Hot pink glow outline
      strokeWidth: 1.5,
      shadowColor: '#FF007F',
      shadowWidth: 2,
      glowColor: '#FF007F',
      glowWidth: 6,
      opacity: 1,
      animation: 'pop',
      position: 'center',
    },
  },
  'luxury': {
    name: 'Cursive Signature',
    style: {
      fontFamily: 'Pacifico',
      fontSize: 28,
      fontWeight: 'normal',
      uppercase: false,
      textColor: '#FFDF00', // Gold Cursive
      textOpacity: 1,
      backgroundColor: '#000000',
      backgroundOpacity: 0,
      strokeColor: '#000000',
      strokeWidth: 1,
      shadowColor: '#000000',
      shadowWidth: 2,
      opacity: 1,
      animation: 'fade',
      position: 'bottom',
    },
  },
  'apple': {
    name: 'Glass Capsule',
    style: {
      fontFamily: 'Outfit',
      fontSize: 22,
      fontWeight: 'bold',
      uppercase: false,
      textColor: '#FFFFFF',
      textOpacity: 1,
      backgroundColor: '#1E1E24',
      backgroundOpacity: 0.7, // rounded glass box
      strokeColor: '#000000',
      strokeWidth: 0,
      shadowColor: '#000000',
      shadowWidth: 0,
      opacity: 1,
      animation: 'slide-up',
      position: 'bottom',
    },
  },
  'floating': {
    name: 'Floating Bold',
    style: {
      fontFamily: 'Anton',
      fontSize: 32,
      fontWeight: 'bold',
      uppercase: true,
      textColor: '#FFFFFF',
      textOpacity: 1,
      backgroundColor: '#000000',
      backgroundOpacity: 0,
      strokeColor: '#000000',
      strokeWidth: 3,
      shadowColor: '#000000',
      shadowWidth: 2,
      opacity: 1,
      animation: 'slide-up',
      position: 'bottom',
    },
  },
  'yellow-pop': {
    name: 'Yellow Anton',
    style: {
      fontFamily: 'Anton',
      fontSize: 32,
      fontWeight: 'bold',
      uppercase: true,
      textColor: '#FFFF00',
      textOpacity: 1,
      backgroundColor: '#000000',
      backgroundOpacity: 0,
      strokeColor: '#000000',
      strokeWidth: 3,
      shadowColor: '#000000',
      shadowWidth: 2,
      opacity: 1,
      animation: 'pop',
      position: 'center',
    },
  },
  'insta-gradient': {
    name: 'Insta Gradient',
    style: {
      fontFamily: 'Poppins',
      fontSize: 26,
      fontWeight: 'bold',
      uppercase: true,
      textColor: '#FFFFFF',
      textOpacity: 1,
      backgroundColor: '#833AB4', // Insta Purple-pink box
      backgroundOpacity: 0.9,
      strokeColor: '#E1306C',
      strokeWidth: 1.5,
      shadowColor: '#FD1D1D',
      shadowWidth: 2,
      glowColor: '#FD1D1D',
      glowWidth: 4,
      opacity: 1,
      animation: 'slide-up',
      position: 'bottom',
    },
  },
  'cyberpunk': {
    name: 'Cyberpunk Neon',
    style: {
      fontFamily: 'Outfit',
      fontSize: 28,
      fontWeight: 'bold',
      uppercase: true,
      textColor: '#00FFFF',
      textOpacity: 1,
      backgroundColor: '#000000',
      backgroundOpacity: 0,
      strokeColor: '#FF00FF',
      strokeWidth: 2,
      shadowColor: '#FF00FF',
      shadowWidth: 2,
      glowColor: '#FF00FF',
      glowWidth: 5,
      opacity: 1,
      animation: 'pop',
      position: 'center',
    },
  },
  'aesthetic-vlog': {
    name: 'Aesthetic Vlog',
    style: {
      fontFamily: 'Playfair Display',
      fontSize: 22,
      fontWeight: 'normal',
      uppercase: false,
      textColor: '#FFFFFF',
      textOpacity: 1,
      backgroundColor: '#000000',
      backgroundOpacity: 0.4,
      strokeColor: '#000000',
      strokeWidth: 0.5,
      shadowColor: '#000000',
      shadowWidth: 0,
      opacity: 1,
      animation: 'fade',
      position: 'bottom',
    },
  },
  'insta-yellow': {
    name: 'Insta Bold Yellow',
    style: {
      fontFamily: 'Anton',
      fontSize: 30,
      fontWeight: 'bold',
      uppercase: true,
      textColor: '#FFFF00',
      textOpacity: 1,
      backgroundColor: '#000000',
      backgroundOpacity: 0,
      strokeColor: '#000000',
      strokeWidth: 2.5,
      shadowColor: '#000000',
      shadowWidth: 0,
      opacity: 1,
      animation: 'pop',
      position: 'bottom',
    },
  },
  'insta-white': {
    name: 'Insta Bold White',
    style: {
      fontFamily: 'Anton',
      fontSize: 30,
      fontWeight: 'bold',
      uppercase: true,
      textColor: '#FFFFFF',
      textOpacity: 1,
      backgroundColor: '#000000',
      backgroundOpacity: 0,
      strokeColor: '#000000',
      strokeWidth: 2.5,
      shadowColor: '#000000',
      shadowWidth: 0,
      opacity: 1,
      animation: 'pop',
      position: 'bottom',
    },
  },
  'insta-squeeze': {
    name: 'Yellow Squeeze',
    style: {
      fontFamily: 'Anton',
      fontSize: 30,
      fontWeight: 'bold',
      uppercase: true,
      textColor: '#FFFF00',
      textOpacity: 1,
      backgroundColor: '#000000',
      backgroundOpacity: 0,
      strokeColor: '#000000',
      strokeWidth: 2.5,
      shadowColor: '#000000',
      shadowWidth: 0,
      opacity: 1,
      animation: 'squeeze',
      position: 'bottom',
    },
  },
};
